//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBaseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANLOG
    {
        public int Id { get; set; }
        public int CanLog1 { get; set; }
        public int CanAct { get; set; }
        public int UsuarioId { get; set; }
        public int TipoPlataformaId { get; set; }
    
        public virtual TIPO_PLATAFORMA TIPO_PLATAFORMA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
