//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBaseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConciergeLogReporting
    {
        public long id { get; set; }
        public int producto { get; set; }
        public System.DateTime fecha { get; set; }
        public string login { get; set; }
        public string usuario { get; set; }
        public string doc_tipo { get; set; }
        public string documento { get; set; }
        public string sucursal { get; set; }
        public string terminal { get; set; }
        public string detalle { get; set; }
        public Nullable<int> tagid { get; set; }
        public Nullable<int> regid { get; set; }
    }
}
