//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBaseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONF_PASSWORD_TYPE
    {
        public int ID_CONF_PASSWORD_TYPE { get; set; }
        public bool AltaAutomatica { get; set; }
        public bool VincularGrupoWindows { get; set; }
        public bool SolicitarContrasenia { get; set; }
        public bool SoloUsuarioLoggeado { get; set; }
        public string TipoSeguridad { get; set; }
    }
}
