//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBaseDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CANLOG> CANLOG { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIA { get; set; }
        public virtual DbSet<CATEGORIA_PROGRAMA> CATEGORIA_PROGRAMA { get; set; }
        public virtual DbSet<CONF_PASSWORD_SESION> CONF_PASSWORD_SESION { get; set; }
        public virtual DbSet<FEATURE> FEATURE { get; set; }
        public virtual DbSet<FUNCION> FUNCION { get; set; }
        public virtual DbSet<FUNCIONALIDAD> FUNCIONALIDAD { get; set; }
        public virtual DbSet<LOG_PLATAFORMA> LOG_PLATAFORMA { get; set; }
        public virtual DbSet<MODO_EXCLUSIVO> MODO_EXCLUSIVO { get; set; }
        public virtual DbSet<PERFIL> PERFIL { get; set; }
        public virtual DbSet<PERFIL_GRUPO_WINDOWS> PERFIL_GRUPO_WINDOWS { get; set; }
        public virtual DbSet<PERFIL_PRODUCTO> PERFIL_PRODUCTO { get; set; }
        public virtual DbSet<PERMISO_FUNCIONALIDAD> PERMISO_FUNCIONALIDAD { get; set; }
        public virtual DbSet<PERMISO_USUARIO> PERMISO_USUARIO { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PRODUCTO_CATEGORIA> PRODUCTO_CATEGORIA { get; set; }
        public virtual DbSet<PROGRAMA> PROGRAMA { get; set; }
        public virtual DbSet<SCHEMA_MIGRATION_GRANTS_LOG> SCHEMA_MIGRATION_GRANTS_LOG { get; set; }
        public virtual DbSet<SCHEMA_MIGRATION_LOG> SCHEMA_MIGRATION_LOG { get; set; }
        public virtual DbSet<SECTOR> SECTOR { get; set; }
        public virtual DbSet<SUCURSAL> SUCURSAL { get; set; }
        public virtual DbSet<TIPO_DOCUMENTO> TIPO_DOCUMENTO { get; set; }
        public virtual DbSet<TIPO_PLATAFORMA> TIPO_PLATAFORMA { get; set; }
        public virtual DbSet<ULTIMAS_PASSWORD> ULTIMAS_PASSWORD { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<USUARIO_INICIO> USUARIO_INICIO { get; set; }
        public virtual DbSet<USUARIO_PASSWORD> USUARIO_PASSWORD { get; set; }
        public virtual DbSet<USUARIO_PERFIL> USUARIO_PERFIL { get; set; }
        public virtual DbSet<USUARIO_SUCURSAL> USUARIO_SUCURSAL { get; set; }
        public virtual DbSet<USUARIO_TERMINAL> USUARIO_TERMINAL { get; set; }
        public virtual DbSet<ConciergeLogReporting> ConciergeLogReporting { get; set; }
        public virtual DbSet<CONF_PASSWORD_TYPE> CONF_PASSWORD_TYPE { get; set; }
        public virtual DbSet<OperationLog> OperationLog { get; set; }
        public virtual DbSet<PROGRAMA_PANTALLA> PROGRAMA_PANTALLA { get; set; }
        public virtual DbSet<RPT_Producto> RPT_Producto { get; set; }
        public virtual DbSet<RPT_Usuario> RPT_Usuario { get; set; }
        public virtual DbSet<RPT_USUARIO_SUCURSAL> RPT_USUARIO_SUCURSAL { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
    
        [DbFunction("Entities", "FnSplit")]
        public virtual IQueryable<FnSplit_Result> FnSplit(string list, string splitOn)
        {
            var listParameter = list != null ?
                new ObjectParameter("List", list) :
                new ObjectParameter("List", typeof(string));
    
            var splitOnParameter = splitOn != null ?
                new ObjectParameter("SplitOn", splitOn) :
                new ObjectParameter("SplitOn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FnSplit_Result>("[Entities].[FnSplit](@List, @SplitOn)", listParameter, splitOnParameter);
        }
    
        public virtual int SP_Create_Funcionalidad(Nullable<int> prodId, Nullable<int> categoriaId, Nullable<int> progId, Nullable<int> funcionId)
        {
            var prodIdParameter = prodId.HasValue ?
                new ObjectParameter("ProdId", prodId) :
                new ObjectParameter("ProdId", typeof(int));
    
            var categoriaIdParameter = categoriaId.HasValue ?
                new ObjectParameter("CategoriaId", categoriaId) :
                new ObjectParameter("CategoriaId", typeof(int));
    
            var progIdParameter = progId.HasValue ?
                new ObjectParameter("ProgId", progId) :
                new ObjectParameter("ProgId", typeof(int));
    
            var funcionIdParameter = funcionId.HasValue ?
                new ObjectParameter("FuncionId", funcionId) :
                new ObjectParameter("FuncionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Create_Funcionalidad", prodIdParameter, categoriaIdParameter, progIdParameter, funcionIdParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SP_Create_Perfil(string codigo, string descripcion)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SP_Create_Perfil", codigoParameter, descripcionParameter);
        }
    
        public virtual int SP_Create_Permiso_Funcionalidad(Nullable<int> perfilId, Nullable<int> prodId, Nullable<int> categoriaId, Nullable<int> progId, Nullable<int> funcionId, Nullable<int> funcionalidadId)
        {
            var perfilIdParameter = perfilId.HasValue ?
                new ObjectParameter("PerfilId", perfilId) :
                new ObjectParameter("PerfilId", typeof(int));
    
            var prodIdParameter = prodId.HasValue ?
                new ObjectParameter("ProdId", prodId) :
                new ObjectParameter("ProdId", typeof(int));
    
            var categoriaIdParameter = categoriaId.HasValue ?
                new ObjectParameter("CategoriaId", categoriaId) :
                new ObjectParameter("CategoriaId", typeof(int));
    
            var progIdParameter = progId.HasValue ?
                new ObjectParameter("ProgId", progId) :
                new ObjectParameter("ProgId", typeof(int));
    
            var funcionIdParameter = funcionId.HasValue ?
                new ObjectParameter("FuncionId", funcionId) :
                new ObjectParameter("FuncionId", typeof(int));
    
            var funcionalidadIdParameter = funcionalidadId.HasValue ?
                new ObjectParameter("FuncionalidadId", funcionalidadId) :
                new ObjectParameter("FuncionalidadId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Create_Permiso_Funcionalidad", perfilIdParameter, prodIdParameter, categoriaIdParameter, progIdParameter, funcionIdParameter, funcionalidadIdParameter);
        }
    
        public virtual int SP_Create_Permiso_Usuario(Nullable<bool> permiso, Nullable<int> usuarioId, Nullable<int> prodId, Nullable<int> categoriaId, Nullable<int> progId, Nullable<int> funcionId)
        {
            var permisoParameter = permiso.HasValue ?
                new ObjectParameter("Permiso", permiso) :
                new ObjectParameter("Permiso", typeof(bool));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var prodIdParameter = prodId.HasValue ?
                new ObjectParameter("ProdId", prodId) :
                new ObjectParameter("ProdId", typeof(int));
    
            var categoriaIdParameter = categoriaId.HasValue ?
                new ObjectParameter("CategoriaId", categoriaId) :
                new ObjectParameter("CategoriaId", typeof(int));
    
            var progIdParameter = progId.HasValue ?
                new ObjectParameter("ProgId", progId) :
                new ObjectParameter("ProgId", typeof(int));
    
            var funcionIdParameter = funcionId.HasValue ?
                new ObjectParameter("FuncionId", funcionId) :
                new ObjectParameter("FuncionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Create_Permiso_Usuario", permisoParameter, usuarioIdParameter, prodIdParameter, categoriaIdParameter, progIdParameter, funcionIdParameter);
        }
    
        public virtual int SP_Create_Producto(string codigo, string descripcion, string base_Path, Nullable<int> tipoPlataformaId, string rama)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var base_PathParameter = base_Path != null ?
                new ObjectParameter("Base_Path", base_Path) :
                new ObjectParameter("Base_Path", typeof(string));
    
            var tipoPlataformaIdParameter = tipoPlataformaId.HasValue ?
                new ObjectParameter("TipoPlataformaId", tipoPlataformaId) :
                new ObjectParameter("TipoPlataformaId", typeof(int));
    
            var ramaParameter = rama != null ?
                new ObjectParameter("Rama", rama) :
                new ObjectParameter("Rama", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Create_Producto", codigoParameter, descripcionParameter, base_PathParameter, tipoPlataformaIdParameter, ramaParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Sp_Create_Ultimas_Password(Nullable<int> userId, string pass)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Sp_Create_Ultimas_Password", userIdParameter, passParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> SP_Create_Usuario(string login, string nombre, string codigo_Persona, string email, Nullable<int> dias_Vigencia_Clave, string login_NT, Nullable<bool> bloqueado, Nullable<bool> bloqueado_Inactividad, string clave, Nullable<bool> cambio_Clave, Nullable<int> cant_Cambios_Clave, Nullable<System.DateTime> ultimo_Cambio_Clave, Nullable<bool> activo, Nullable<int> sectorId, Nullable<int> tipoDocumentoId, Nullable<int> documento)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigo_PersonaParameter = codigo_Persona != null ?
                new ObjectParameter("Codigo_Persona", codigo_Persona) :
                new ObjectParameter("Codigo_Persona", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var dias_Vigencia_ClaveParameter = dias_Vigencia_Clave.HasValue ?
                new ObjectParameter("Dias_Vigencia_Clave", dias_Vigencia_Clave) :
                new ObjectParameter("Dias_Vigencia_Clave", typeof(int));
    
            var login_NTParameter = login_NT != null ?
                new ObjectParameter("Login_NT", login_NT) :
                new ObjectParameter("Login_NT", typeof(string));
    
            var bloqueadoParameter = bloqueado.HasValue ?
                new ObjectParameter("Bloqueado", bloqueado) :
                new ObjectParameter("Bloqueado", typeof(bool));
    
            var bloqueado_InactividadParameter = bloqueado_Inactividad.HasValue ?
                new ObjectParameter("Bloqueado_Inactividad", bloqueado_Inactividad) :
                new ObjectParameter("Bloqueado_Inactividad", typeof(bool));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            var cambio_ClaveParameter = cambio_Clave.HasValue ?
                new ObjectParameter("Cambio_Clave", cambio_Clave) :
                new ObjectParameter("Cambio_Clave", typeof(bool));
    
            var cant_Cambios_ClaveParameter = cant_Cambios_Clave.HasValue ?
                new ObjectParameter("Cant_Cambios_Clave", cant_Cambios_Clave) :
                new ObjectParameter("Cant_Cambios_Clave", typeof(int));
    
            var ultimo_Cambio_ClaveParameter = ultimo_Cambio_Clave.HasValue ?
                new ObjectParameter("Ultimo_Cambio_Clave", ultimo_Cambio_Clave) :
                new ObjectParameter("Ultimo_Cambio_Clave", typeof(System.DateTime));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            var sectorIdParameter = sectorId.HasValue ?
                new ObjectParameter("SectorId", sectorId) :
                new ObjectParameter("SectorId", typeof(int));
    
            var tipoDocumentoIdParameter = tipoDocumentoId.HasValue ?
                new ObjectParameter("TipoDocumentoId", tipoDocumentoId) :
                new ObjectParameter("TipoDocumentoId", typeof(int));
    
            var documentoParameter = documento.HasValue ?
                new ObjectParameter("Documento", documento) :
                new ObjectParameter("Documento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("SP_Create_Usuario", loginParameter, nombreParameter, codigo_PersonaParameter, emailParameter, dias_Vigencia_ClaveParameter, login_NTParameter, bloqueadoParameter, bloqueado_InactividadParameter, claveParameter, cambio_ClaveParameter, cant_Cambios_ClaveParameter, ultimo_Cambio_ClaveParameter, activoParameter, sectorIdParameter, tipoDocumentoIdParameter, documentoParameter);
        }
    
        public virtual int SP_Create_Usuario_Inicio(Nullable<int> productId, Nullable<int> categoryId, Nullable<int> userId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(int));
    
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Create_Usuario_Inicio", productIdParameter, categoryIdParameter, userIdParameter);
        }
    
        public virtual int SP_Create_Usuario_Perfil(Nullable<int> usuarioId, Nullable<int> perfilId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var perfilIdParameter = perfilId.HasValue ?
                new ObjectParameter("PerfilId", perfilId) :
                new ObjectParameter("PerfilId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Create_Usuario_Perfil", usuarioIdParameter, perfilIdParameter);
        }
    
        public virtual int SP_Create_Usuario_Sucursal(Nullable<int> userId, Nullable<int> sucursalId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var sucursalIdParameter = sucursalId.HasValue ?
                new ObjectParameter("SucursalId", sucursalId) :
                new ObjectParameter("SucursalId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Create_Usuario_Sucursal", userIdParameter, sucursalIdParameter);
        }
    
        public virtual int SP_Delete_Canlog_By_Usuario_Id(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Delete_Canlog_By_Usuario_Id", userIdParameter);
        }
    
        public virtual int SP_Delete_Modo_Exclusivo(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Delete_Modo_Exclusivo", usuarioIdParameter);
        }
    
        public virtual int SP_Delete_Perfil(Nullable<int> perfilId)
        {
            var perfilIdParameter = perfilId.HasValue ?
                new ObjectParameter("PerfilId", perfilId) :
                new ObjectParameter("PerfilId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Delete_Perfil", perfilIdParameter);
        }
    
        public virtual int SP_Delete_Perfil_Producto(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Delete_Perfil_Producto", profileIdParameter);
        }
    
        public virtual int SP_Delete_Perfil_Usuario(Nullable<int> perfilId)
        {
            var perfilIdParameter = perfilId.HasValue ?
                new ObjectParameter("PerfilId", perfilId) :
                new ObjectParameter("PerfilId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Delete_Perfil_Usuario", perfilIdParameter);
        }
    
        public virtual int Sp_Delete_Permiso_Funcionalidad(Nullable<int> perfilId, Nullable<int> prodId, Nullable<int> categoriaId, Nullable<int> progId, Nullable<int> funcionId, Nullable<int> funcionalidadId)
        {
            var perfilIdParameter = perfilId.HasValue ?
                new ObjectParameter("PerfilId", perfilId) :
                new ObjectParameter("PerfilId", typeof(int));
    
            var prodIdParameter = prodId.HasValue ?
                new ObjectParameter("ProdId", prodId) :
                new ObjectParameter("ProdId", typeof(int));
    
            var categoriaIdParameter = categoriaId.HasValue ?
                new ObjectParameter("CategoriaId", categoriaId) :
                new ObjectParameter("CategoriaId", typeof(int));
    
            var progIdParameter = progId.HasValue ?
                new ObjectParameter("ProgId", progId) :
                new ObjectParameter("ProgId", typeof(int));
    
            var funcionIdParameter = funcionId.HasValue ?
                new ObjectParameter("FuncionId", funcionId) :
                new ObjectParameter("FuncionId", typeof(int));
    
            var funcionalidadIdParameter = funcionalidadId.HasValue ?
                new ObjectParameter("FuncionalidadId", funcionalidadId) :
                new ObjectParameter("FuncionalidadId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Delete_Permiso_Funcionalidad", perfilIdParameter, prodIdParameter, categoriaIdParameter, progIdParameter, funcionIdParameter, funcionalidadIdParameter);
        }
    
        public virtual int SP_Delete_Permiso_Usuario(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Delete_Permiso_Usuario", usuarioIdParameter);
        }
    
        public virtual ObjectResult<SP_Delete_Usuario_Result> SP_Delete_Usuario(Nullable<int> usuarioId, Nullable<int> currentUser, Nullable<System.DateTime> fechaEliminado)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var currentUserParameter = currentUser.HasValue ?
                new ObjectParameter("CurrentUser", currentUser) :
                new ObjectParameter("CurrentUser", typeof(int));
    
            var fechaEliminadoParameter = fechaEliminado.HasValue ?
                new ObjectParameter("FechaEliminado", fechaEliminado) :
                new ObjectParameter("FechaEliminado", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Delete_Usuario_Result>("SP_Delete_Usuario", usuarioIdParameter, currentUserParameter, fechaEliminadoParameter);
        }
    
        public virtual int SP_Delete_Usuario_Perfil(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Delete_Usuario_Perfil", usuarioIdParameter);
        }
    
        public virtual int SP_Delete_Usuario_Perfil_Login(Nullable<int> usuarioId, Nullable<int> perfilId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var perfilIdParameter = perfilId.HasValue ?
                new ObjectParameter("PerfilId", perfilId) :
                new ObjectParameter("PerfilId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Delete_Usuario_Perfil_Login", usuarioIdParameter, perfilIdParameter);
        }
    
        public virtual int SP_Delete_Usuario_Sucursal(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Delete_Usuario_Sucursal", userIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_All_LoginUsers_Result> SP_Get_All_LoginUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_All_LoginUsers_Result>("SP_Get_All_LoginUsers");
        }
    
        public virtual ObjectResult<SP_Get_All_LoginUsers_Able_Result> SP_Get_All_LoginUsers_Able()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_All_LoginUsers_Able_Result>("SP_Get_All_LoginUsers_Able");
        }
    
        public virtual ObjectResult<SP_Get_All_Users_By_Distinct_Profile_Result> SP_Get_All_Users_By_Distinct_Profile(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_All_Users_By_Distinct_Profile_Result>("SP_Get_All_Users_By_Distinct_Profile", profileIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_All_Usuarios_Result> SP_Get_All_Usuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_All_Usuarios_Result>("SP_Get_All_Usuarios");
        }
    
        public virtual ObjectResult<SP_Get_All_Usuarios_By_Profile_Result> SP_Get_All_Usuarios_By_Profile(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_All_Usuarios_By_Profile_Result>("SP_Get_All_Usuarios_By_Profile", profileIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Canlog_By_Usuario_Id_Result> SP_Get_Canlog_By_Usuario_Id(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Canlog_By_Usuario_Id_Result>("SP_Get_Canlog_By_Usuario_Id", usuarioIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_Get_Cantidad_Usuarios_Perfil(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Get_Cantidad_Usuarios_Perfil", profileIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Categorias_Result> SP_Get_Categorias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Categorias_Result>("SP_Get_Categorias");
        }
    
        public virtual ObjectResult<SP_Get_Categorias_By_Perfil_Result> SP_Get_Categorias_By_Perfil(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Categorias_By_Perfil_Result>("SP_Get_Categorias_By_Perfil", profileIdParameter);
        }
    
        public virtual ObjectResult<string> SP_Get_Claims_By_Login(string userLogin)
        {
            var userLoginParameter = userLogin != null ?
                new ObjectParameter("UserLogin", userLogin) :
                new ObjectParameter("UserLogin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Get_Claims_By_Login", userLoginParameter);
        }
    
        public virtual ObjectResult<SP_Get_Configuration_Password_Sesion_Result> SP_Get_Configuration_Password_Sesion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Configuration_Password_Sesion_Result>("SP_Get_Configuration_Password_Sesion");
        }
    
        public virtual ObjectResult<SP_Get_Configuration_Password_Type_Result> SP_Get_Configuration_Password_Type()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Configuration_Password_Type_Result>("SP_Get_Configuration_Password_Type");
        }
    
        public virtual ObjectResult<SP_Get_Entidad_Bancaria_Result> SP_Get_Entidad_Bancaria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Entidad_Bancaria_Result>("SP_Get_Entidad_Bancaria");
        }
    
        public virtual ObjectResult<SP_Get_Funcionalidad_Result> SP_Get_Funcionalidad(Nullable<int> prodId, Nullable<int> categoriaId, Nullable<int> progId, Nullable<int> funcionId)
        {
            var prodIdParameter = prodId.HasValue ?
                new ObjectParameter("ProdId", prodId) :
                new ObjectParameter("ProdId", typeof(int));
    
            var categoriaIdParameter = categoriaId.HasValue ?
                new ObjectParameter("CategoriaId", categoriaId) :
                new ObjectParameter("CategoriaId", typeof(int));
    
            var progIdParameter = progId.HasValue ?
                new ObjectParameter("ProgId", progId) :
                new ObjectParameter("ProgId", typeof(int));
    
            var funcionIdParameter = funcionId.HasValue ?
                new ObjectParameter("FuncionId", funcionId) :
                new ObjectParameter("FuncionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Funcionalidad_Result>("SP_Get_Funcionalidad", prodIdParameter, categoriaIdParameter, progIdParameter, funcionIdParameter);
        }
    
        public virtual int SP_Get_Funcionalidad_By_Function(Nullable<int> profileId, Nullable<int> product, Nullable<int> category, Nullable<int> program)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var productParameter = product.HasValue ?
                new ObjectParameter("product", product) :
                new ObjectParameter("product", typeof(int));
    
            var categoryParameter = category.HasValue ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(int));
    
            var programParameter = program.HasValue ?
                new ObjectParameter("program", program) :
                new ObjectParameter("program", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Get_Funcionalidad_By_Function", profileIdParameter, productParameter, categoryParameter, programParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_Get_Funcionalidad_By_Perfil(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Get_Funcionalidad_By_Perfil", profileIdParameter);
        }
    
        public virtual int SP_Get_Funcionalidades_By_Usuario(string userId, string producto, string categoria, string programa)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            var productoParameter = producto != null ?
                new ObjectParameter("producto", producto) :
                new ObjectParameter("producto", typeof(string));
    
            var categoriaParameter = categoria != null ?
                new ObjectParameter("categoria", categoria) :
                new ObjectParameter("categoria", typeof(string));
    
            var programaParameter = programa != null ?
                new ObjectParameter("programa", programa) :
                new ObjectParameter("programa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Get_Funcionalidades_By_Usuario", userIdParameter, productoParameter, categoriaParameter, programaParameter);
        }
    
        public virtual ObjectResult<SP_Get_Funciones_Result> SP_Get_Funciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Funciones_Result>("SP_Get_Funciones");
        }
    
        public virtual ObjectResult<SP_Get_Functions_By_Permission_Result> SP_Get_Functions_By_Permission(Nullable<int> product, Nullable<int> category, Nullable<int> program)
        {
            var productParameter = product.HasValue ?
                new ObjectParameter("product", product) :
                new ObjectParameter("product", typeof(int));
    
            var categoryParameter = category.HasValue ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(int));
    
            var programParameter = program.HasValue ?
                new ObjectParameter("program", program) :
                new ObjectParameter("program", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Functions_By_Permission_Result>("SP_Get_Functions_By_Permission", productParameter, categoryParameter, programParameter);
        }
    
        public virtual ObjectResult<SP_Get_Initial_Data_Navbar_Result> SP_Get_Initial_Data_Navbar(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Initial_Data_Navbar_Result>("SP_Get_Initial_Data_Navbar", userIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Log_Plataforma_By_Usuario_Id_Result> SP_Get_Log_Plataforma_By_Usuario_Id(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Log_Plataforma_By_Usuario_Id_Result>("SP_Get_Log_Plataforma_By_Usuario_Id", userIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Menu_By_Usuario_Id_Result> SP_Get_Menu_By_Usuario_Id(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Menu_By_Usuario_Id_Result>("SP_Get_Menu_By_Usuario_Id", usuarioIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Modo_Exclusivo_By_User_Id_Result> SP_Get_Modo_Exclusivo_By_User_Id(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Modo_Exclusivo_By_User_Id_Result>("SP_Get_Modo_Exclusivo_By_User_Id", userIdParameter);
        }
    
        public virtual ObjectResult<Sp_Get_Perfil_By_Id_Result> Sp_Get_Perfil_By_Id(Nullable<int> perfilId)
        {
            var perfilIdParameter = perfilId.HasValue ?
                new ObjectParameter("PerfilId", perfilId) :
                new ObjectParameter("PerfilId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Get_Perfil_By_Id_Result>("Sp_Get_Perfil_By_Id", perfilIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_PERFIL_GRUPO_WINDOWS_Result> SP_GET_PERFIL_GRUPO_WINDOWS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_PERFIL_GRUPO_WINDOWS_Result>("SP_GET_PERFIL_GRUPO_WINDOWS");
        }
    
        public virtual ObjectResult<SP_Get_Perfil_Usuario_Result> SP_Get_Perfil_Usuario(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Perfil_Usuario_Result>("SP_Get_Perfil_Usuario", usuarioIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Perfiles_Result> SP_Get_Perfiles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Perfiles_Result>("SP_Get_Perfiles");
        }
    
        public virtual ObjectResult<SP_Get_Perfiles_By_Producto_Result> SP_Get_Perfiles_By_Producto(Nullable<int> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Perfiles_By_Producto_Result>("SP_Get_Perfiles_By_Producto", productIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Perfiles_Permisos_SSRS_Result> SP_Get_Perfiles_Permisos_SSRS(string productoId, string perfilId)
        {
            var productoIdParameter = productoId != null ?
                new ObjectParameter("ProductoId", productoId) :
                new ObjectParameter("ProductoId", typeof(string));
    
            var perfilIdParameter = perfilId != null ?
                new ObjectParameter("PerfilId", perfilId) :
                new ObjectParameter("PerfilId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Perfiles_Permisos_SSRS_Result>("SP_Get_Perfiles_Permisos_SSRS", productoIdParameter, perfilIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Permiso_Funcionalidad_By_Funcionalidad_Result> SP_Get_Permiso_Funcionalidad_By_Funcionalidad(Nullable<int> product, Nullable<int> category, Nullable<int> program)
        {
            var productParameter = product.HasValue ?
                new ObjectParameter("product", product) :
                new ObjectParameter("product", typeof(int));
    
            var categoryParameter = category.HasValue ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(int));
    
            var programParameter = program.HasValue ?
                new ObjectParameter("program", program) :
                new ObjectParameter("program", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Permiso_Funcionalidad_By_Funcionalidad_Result>("SP_Get_Permiso_Funcionalidad_By_Funcionalidad", productParameter, categoryParameter, programParameter);
        }
    
        public virtual int SP_Get_Permisos_By_Perfil(Nullable<int> productoId, Nullable<int> categoriaId, Nullable<int> perfilId, Nullable<int> programaId)
        {
            var productoIdParameter = productoId.HasValue ?
                new ObjectParameter("ProductoId", productoId) :
                new ObjectParameter("ProductoId", typeof(int));
    
            var categoriaIdParameter = categoriaId.HasValue ?
                new ObjectParameter("CategoriaId", categoriaId) :
                new ObjectParameter("CategoriaId", typeof(int));
    
            var perfilIdParameter = perfilId.HasValue ?
                new ObjectParameter("PerfilId", perfilId) :
                new ObjectParameter("PerfilId", typeof(int));
    
            var programaIdParameter = programaId.HasValue ?
                new ObjectParameter("ProgramaId", programaId) :
                new ObjectParameter("ProgramaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Get_Permisos_By_Perfil", productoIdParameter, categoriaIdParameter, perfilIdParameter, programaIdParameter);
        }
    
        public virtual int Sp_Get_Permisos_By_Programa(Nullable<int> productoId, Nullable<int> categoriaId, Nullable<int> programaId)
        {
            var productoIdParameter = productoId.HasValue ?
                new ObjectParameter("ProductoId", productoId) :
                new ObjectParameter("ProductoId", typeof(int));
    
            var categoriaIdParameter = categoriaId.HasValue ?
                new ObjectParameter("CategoriaId", categoriaId) :
                new ObjectParameter("CategoriaId", typeof(int));
    
            var programaIdParameter = programaId.HasValue ?
                new ObjectParameter("ProgramaId", programaId) :
                new ObjectParameter("ProgramaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Get_Permisos_By_Programa", productoIdParameter, categoriaIdParameter, programaIdParameter);
        }
    
        public virtual ObjectResult<Sp_Get_Permisos_By_Usuario_Result> Sp_Get_Permisos_By_Usuario(Nullable<int> productoId, Nullable<int> categoriaId, Nullable<int> programaId, Nullable<int> usuarioId)
        {
            var productoIdParameter = productoId.HasValue ?
                new ObjectParameter("ProductoId", productoId) :
                new ObjectParameter("ProductoId", typeof(int));
    
            var categoriaIdParameter = categoriaId.HasValue ?
                new ObjectParameter("CategoriaId", categoriaId) :
                new ObjectParameter("CategoriaId", typeof(int));
    
            var programaIdParameter = programaId.HasValue ?
                new ObjectParameter("ProgramaId", programaId) :
                new ObjectParameter("ProgramaId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Get_Permisos_By_Usuario_Result>("Sp_Get_Permisos_By_Usuario", productoIdParameter, categoriaIdParameter, programaIdParameter, usuarioIdParameter);
        }
    
        public virtual int SP_Get_Permisos_Usuario_By_Programa(Nullable<int> productoID, Nullable<int> programaId, Nullable<int> categoriaId)
        {
            var productoIDParameter = productoID.HasValue ?
                new ObjectParameter("ProductoID", productoID) :
                new ObjectParameter("ProductoID", typeof(int));
    
            var programaIdParameter = programaId.HasValue ?
                new ObjectParameter("ProgramaId", programaId) :
                new ObjectParameter("ProgramaId", typeof(int));
    
            var categoriaIdParameter = categoriaId.HasValue ?
                new ObjectParameter("CategoriaId", categoriaId) :
                new ObjectParameter("CategoriaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Get_Permisos_Usuario_By_Programa", productoIDParameter, programaIdParameter, categoriaIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Producto_Result> SP_Get_Producto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Producto_Result>("SP_Get_Producto");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_Get_Producto_By_Perfil(Nullable<int> profileId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Get_Producto_By_Perfil", profileIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Productos_By_Usuario_Id_Result> SP_Get_Productos_By_Usuario_Id(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Productos_By_Usuario_Id_Result>("SP_Get_Productos_By_Usuario_Id", usuarioIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Programas_Result> SP_Get_Programas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Programas_Result>("SP_Get_Programas");
        }
    
        public virtual ObjectResult<SP_Get_Route_By_Usuario_Id_Result> SP_Get_Route_By_Usuario_Id(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Route_By_Usuario_Id_Result>("SP_Get_Route_By_Usuario_Id", usuarioIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Sectores_Result> SP_Get_Sectores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Sectores_Result>("SP_Get_Sectores");
        }
    
        public virtual ObjectResult<SP_Get_Sucursal_By_Usuario_Result> SP_Get_Sucursal_By_Usuario(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Sucursal_By_Usuario_Result>("SP_Get_Sucursal_By_Usuario", userIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Sucursal_By_UsuarioId_Result> SP_Get_Sucursal_By_UsuarioId(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Sucursal_By_UsuarioId_Result>("SP_Get_Sucursal_By_UsuarioId", userIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Sucursales_Result> SP_Get_Sucursales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Sucursales_Result>("SP_Get_Sucursales");
        }
    
        public virtual ObjectResult<SP_Get_tipo_documento_Result> SP_Get_tipo_documento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_tipo_documento_Result>("SP_Get_tipo_documento");
        }
    
        public virtual ObjectResult<SP_Get_Tipo_Plataforma_Result> SP_Get_Tipo_Plataforma()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Tipo_Plataforma_Result>("SP_Get_Tipo_Plataforma");
        }
    
        public virtual ObjectResult<Sp_Get_Ultimo_Acceso_Usuario_Result> Sp_Get_Ultimo_Acceso_Usuario(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Get_Ultimo_Acceso_Usuario_Result>("Sp_Get_Ultimo_Acceso_Usuario", usuarioIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Usuario_Result> SP_Get_Usuario(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Usuario_Result>("SP_Get_Usuario", idUsuarioParameter);
        }
    
        public virtual ObjectResult<SP_Get_Usuario_By_Id_Result> SP_Get_Usuario_By_Id(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Usuario_By_Id_Result>("SP_Get_Usuario_By_Id", userIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Usuario_By_LogIn_Result> SP_Get_Usuario_By_LogIn(string login)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Usuario_By_LogIn_Result>("SP_Get_Usuario_By_LogIn", loginParameter);
        }
    
        public virtual ObjectResult<SP_Get_Usuario_By_LogIn_Nt_Result> SP_Get_Usuario_By_LogIn_Nt(string loginNt)
        {
            var loginNtParameter = loginNt != null ?
                new ObjectParameter("LoginNt", loginNt) :
                new ObjectParameter("LoginNt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Usuario_By_LogIn_Nt_Result>("SP_Get_Usuario_By_LogIn_Nt", loginNtParameter);
        }
    
        public virtual ObjectResult<SP_Get_Usuarios_Result> SP_Get_Usuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Usuarios_Result>("SP_Get_Usuarios");
        }
    
        public virtual ObjectResult<SP_Get_Usuarios_Baja_SSRS_Result> SP_Get_Usuarios_Baja_SSRS(string sucursalId, string sectorId)
        {
            var sucursalIdParameter = sucursalId != null ?
                new ObjectParameter("SucursalId", sucursalId) :
                new ObjectParameter("SucursalId", typeof(string));
    
            var sectorIdParameter = sectorId != null ?
                new ObjectParameter("SectorId", sectorId) :
                new ObjectParameter("SectorId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Usuarios_Baja_SSRS_Result>("SP_Get_Usuarios_Baja_SSRS", sucursalIdParameter, sectorIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Usuarios_Inactivos_Result> SP_Get_Usuarios_Inactivos(string sucursalId, string sectorId)
        {
            var sucursalIdParameter = sucursalId != null ?
                new ObjectParameter("SucursalId", sucursalId) :
                new ObjectParameter("SucursalId", typeof(string));
    
            var sectorIdParameter = sectorId != null ?
                new ObjectParameter("SectorId", sectorId) :
                new ObjectParameter("SectorId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Usuarios_Inactivos_Result>("SP_Get_Usuarios_Inactivos", sucursalIdParameter, sectorIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Usuarios_Permisos_SSRS_Result> SP_Get_Usuarios_Permisos_SSRS(string productoId, string perfilId, string loginId, string sucursalId, string sectorId)
        {
            var productoIdParameter = productoId != null ?
                new ObjectParameter("ProductoId", productoId) :
                new ObjectParameter("ProductoId", typeof(string));
    
            var perfilIdParameter = perfilId != null ?
                new ObjectParameter("PerfilId", perfilId) :
                new ObjectParameter("PerfilId", typeof(string));
    
            var loginIdParameter = loginId != null ?
                new ObjectParameter("LoginId", loginId) :
                new ObjectParameter("LoginId", typeof(string));
    
            var sucursalIdParameter = sucursalId != null ?
                new ObjectParameter("SucursalId", sucursalId) :
                new ObjectParameter("SucursalId", typeof(string));
    
            var sectorIdParameter = sectorId != null ?
                new ObjectParameter("SectorId", sectorId) :
                new ObjectParameter("SectorId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Usuarios_Permisos_SSRS_Result>("SP_Get_Usuarios_Permisos_SSRS", productoIdParameter, perfilIdParameter, loginIdParameter, sucursalIdParameter, sectorIdParameter);
        }
    
        public virtual int SP_Get_Usuarios_Sin_Ingreso(string sucursalId, string sectorId)
        {
            var sucursalIdParameter = sucursalId != null ?
                new ObjectParameter("SucursalId", sucursalId) :
                new ObjectParameter("SucursalId", typeof(string));
    
            var sectorIdParameter = sectorId != null ?
                new ObjectParameter("SectorId", sectorId) :
                new ObjectParameter("SectorId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Get_Usuarios_Sin_Ingreso", sucursalIdParameter, sectorIdParameter);
        }
    
        public virtual ObjectResult<SP_Get_Usuarios_SSRS_Result> SP_Get_Usuarios_SSRS(string sucursalId, string sectorId)
        {
            var sucursalIdParameter = sucursalId != null ?
                new ObjectParameter("SucursalId", sucursalId) :
                new ObjectParameter("SucursalId", typeof(string));
    
            var sectorIdParameter = sectorId != null ?
                new ObjectParameter("SectorId", sectorId) :
                new ObjectParameter("SectorId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Get_Usuarios_SSRS_Result>("SP_Get_Usuarios_SSRS", sucursalIdParameter, sectorIdParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> SP_GET_Validar_Caducidad(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("usuarioId", usuarioId) :
                new ObjectParameter("usuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("SP_GET_Validar_Caducidad", usuarioIdParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> SP_GET_Validar_Tiempo_Inactividad(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("usuarioId", usuarioId) :
                new ObjectParameter("usuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("SP_GET_Validar_Tiempo_Inactividad", usuarioIdParameter);
        }
    
        public virtual int SP_Insert_Canlog_By_Usuario_Id(Nullable<int> canLog, Nullable<int> canAct, Nullable<int> usuarioId, Nullable<int> tipoPlataformaId)
        {
            var canLogParameter = canLog.HasValue ?
                new ObjectParameter("CanLog", canLog) :
                new ObjectParameter("CanLog", typeof(int));
    
            var canActParameter = canAct.HasValue ?
                new ObjectParameter("CanAct", canAct) :
                new ObjectParameter("CanAct", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var tipoPlataformaIdParameter = tipoPlataformaId.HasValue ?
                new ObjectParameter("TipoPlataformaId", tipoPlataformaId) :
                new ObjectParameter("TipoPlataformaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Insert_Canlog_By_Usuario_Id", canLogParameter, canActParameter, usuarioIdParameter, tipoPlataformaIdParameter);
        }
    
        public virtual int SP_Insert_Canlog_Login(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Insert_Canlog_Login", usuarioIdParameter);
        }
    
        public virtual int SP_Insert_Modo_Exclusivo(Nullable<int> productoId, Nullable<int> usuarioId)
        {
            var productoIdParameter = productoId.HasValue ?
                new ObjectParameter("ProductoId", productoId) :
                new ObjectParameter("ProductoId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Insert_Modo_Exclusivo", productoIdParameter, usuarioIdParameter);
        }
    
        public virtual int SP_Insert_Perfil_Producto(Nullable<int> profileId, Nullable<int> productId)
        {
            var profileIdParameter = profileId.HasValue ?
                new ObjectParameter("ProfileId", profileId) :
                new ObjectParameter("ProfileId", typeof(int));
    
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Insert_Perfil_Producto", profileIdParameter, productIdParameter);
        }
    
        public virtual int SP_Insert_Permiso_Funcionalidad(Nullable<int> perfilId, Nullable<int> prodId, Nullable<int> categoriaId, Nullable<int> progId, Nullable<int> funcionId, Nullable<int> funcionalidadId)
        {
            var perfilIdParameter = perfilId.HasValue ?
                new ObjectParameter("PerfilId", perfilId) :
                new ObjectParameter("PerfilId", typeof(int));
    
            var prodIdParameter = prodId.HasValue ?
                new ObjectParameter("ProdId", prodId) :
                new ObjectParameter("ProdId", typeof(int));
    
            var categoriaIdParameter = categoriaId.HasValue ?
                new ObjectParameter("CategoriaId", categoriaId) :
                new ObjectParameter("CategoriaId", typeof(int));
    
            var progIdParameter = progId.HasValue ?
                new ObjectParameter("ProgId", progId) :
                new ObjectParameter("ProgId", typeof(int));
    
            var funcionIdParameter = funcionId.HasValue ?
                new ObjectParameter("FuncionId", funcionId) :
                new ObjectParameter("FuncionId", typeof(int));
    
            var funcionalidadIdParameter = funcionalidadId.HasValue ?
                new ObjectParameter("FuncionalidadId", funcionalidadId) :
                new ObjectParameter("FuncionalidadId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Insert_Permiso_Funcionalidad", perfilIdParameter, prodIdParameter, categoriaIdParameter, progIdParameter, funcionIdParameter, funcionalidadIdParameter);
        }
    
        public virtual int Sp_Insert_Usuario_Perfil(Nullable<int> usuarioId, Nullable<int> perfilId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var perfilIdParameter = perfilId.HasValue ?
                new ObjectParameter("PerfilId", perfilId) :
                new ObjectParameter("PerfilId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Insert_Usuario_Perfil", usuarioIdParameter, perfilIdParameter);
        }
    
        public virtual ObjectResult<SP_Lock_Usuario_Result> SP_Lock_Usuario(Nullable<int> usuarioId, Nullable<int> currentUser, Nullable<System.DateTime> fechaBloqueado)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var currentUserParameter = currentUser.HasValue ?
                new ObjectParameter("CurrentUser", currentUser) :
                new ObjectParameter("CurrentUser", typeof(int));
    
            var fechaBloqueadoParameter = fechaBloqueado.HasValue ?
                new ObjectParameter("FechaBloqueado", fechaBloqueado) :
                new ObjectParameter("FechaBloqueado", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Lock_Usuario_Result>("SP_Lock_Usuario", usuarioIdParameter, currentUserParameter, fechaBloqueadoParameter);
        }
    
        public virtual int Sp_Set_Cambio_Clave(Nullable<int> usuarioId, Nullable<bool> cambioClave)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var cambioClaveParameter = cambioClave.HasValue ?
                new ObjectParameter("CambioClave", cambioClave) :
                new ObjectParameter("CambioClave", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Set_Cambio_Clave", usuarioIdParameter, cambioClaveParameter);
        }
    
        public virtual int SP_Set_Motivo_Bloqueo(Nullable<int> usuarioId, string motivoBloqueo)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var motivoBloqueoParameter = motivoBloqueo != null ?
                new ObjectParameter("MotivoBloqueo", motivoBloqueo) :
                new ObjectParameter("MotivoBloqueo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Set_Motivo_Bloqueo", usuarioIdParameter, motivoBloqueoParameter);
        }
    
        public virtual int SP_Set_Register_End_Session(Nullable<int> usuarioId, Nullable<int> tipoPlataformaId, string terminalId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var tipoPlataformaIdParameter = tipoPlataformaId.HasValue ?
                new ObjectParameter("TipoPlataformaId", tipoPlataformaId) :
                new ObjectParameter("TipoPlataformaId", typeof(int));
    
            var terminalIdParameter = terminalId != null ?
                new ObjectParameter("TerminalId", terminalId) :
                new ObjectParameter("TerminalId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Set_Register_End_Session", usuarioIdParameter, tipoPlataformaIdParameter, terminalIdParameter);
        }
    
        public virtual int SP_Set_Register_Start_Session(Nullable<int> usuarioId, Nullable<int> tipoPlataformaId, string terminalId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var tipoPlataformaIdParameter = tipoPlataformaId.HasValue ?
                new ObjectParameter("TipoPlataformaId", tipoPlataformaId) :
                new ObjectParameter("TipoPlataformaId", typeof(int));
    
            var terminalIdParameter = terminalId != null ?
                new ObjectParameter("TerminalId", terminalId) :
                new ObjectParameter("TerminalId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Set_Register_Start_Session", usuarioIdParameter, tipoPlataformaIdParameter, terminalIdParameter);
        }
    
        public virtual int Sp_Set_User_State(Nullable<int> usuarioId, Nullable<bool> activo)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Set_User_State", usuarioIdParameter, activoParameter);
        }
    
        public virtual int SP_Unlock_Usuario(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Unlock_Usuario", userIdParameter);
        }
    
        public virtual int SP_Update_Canlog(Nullable<int> tipoPlataformaId, Nullable<int> usuarioId, Nullable<int> accesos)
        {
            var tipoPlataformaIdParameter = tipoPlataformaId.HasValue ?
                new ObjectParameter("TipoPlataformaId", tipoPlataformaId) :
                new ObjectParameter("TipoPlataformaId", typeof(int));
    
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var accesosParameter = accesos.HasValue ?
                new ObjectParameter("Accesos", accesos) :
                new ObjectParameter("Accesos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Update_Canlog", tipoPlataformaIdParameter, usuarioIdParameter, accesosParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Sp_Update_Changing_Password(Nullable<int> userId, string newPass)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            var newPassParameter = newPass != null ?
                new ObjectParameter("NewPass", newPass) :
                new ObjectParameter("NewPass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Sp_Update_Changing_Password", userIdParameter, newPassParameter);
        }
    
        public virtual int SP_UPDATE_CONF_PASSWORD_SESION(Nullable<bool> alfabetica, Nullable<bool> numerica, Nullable<bool> caracteresEspeciales, Nullable<bool> permiteNrosConsecutivos, Nullable<bool> permiteLetrasConsecutivas, Nullable<bool> permiteRepetirPosicion, Nullable<bool> permiteCaracteresIguales, Nullable<bool> caseSensitive, Nullable<int> caracteresMinimos, Nullable<int> cantidadRepeticiones, Nullable<int> maxDiasInactividad, Nullable<int> maxDiasCaducidad, Nullable<int> minutosPermitidosInactividad, Nullable<int> cantIntentosFallidos)
        {
            var alfabeticaParameter = alfabetica.HasValue ?
                new ObjectParameter("Alfabetica", alfabetica) :
                new ObjectParameter("Alfabetica", typeof(bool));
    
            var numericaParameter = numerica.HasValue ?
                new ObjectParameter("Numerica", numerica) :
                new ObjectParameter("Numerica", typeof(bool));
    
            var caracteresEspecialesParameter = caracteresEspeciales.HasValue ?
                new ObjectParameter("CaracteresEspeciales", caracteresEspeciales) :
                new ObjectParameter("CaracteresEspeciales", typeof(bool));
    
            var permiteNrosConsecutivosParameter = permiteNrosConsecutivos.HasValue ?
                new ObjectParameter("PermiteNrosConsecutivos", permiteNrosConsecutivos) :
                new ObjectParameter("PermiteNrosConsecutivos", typeof(bool));
    
            var permiteLetrasConsecutivasParameter = permiteLetrasConsecutivas.HasValue ?
                new ObjectParameter("PermiteLetrasConsecutivas", permiteLetrasConsecutivas) :
                new ObjectParameter("PermiteLetrasConsecutivas", typeof(bool));
    
            var permiteRepetirPosicionParameter = permiteRepetirPosicion.HasValue ?
                new ObjectParameter("PermiteRepetirPosicion", permiteRepetirPosicion) :
                new ObjectParameter("PermiteRepetirPosicion", typeof(bool));
    
            var permiteCaracteresIgualesParameter = permiteCaracteresIguales.HasValue ?
                new ObjectParameter("PermiteCaracteresIguales", permiteCaracteresIguales) :
                new ObjectParameter("PermiteCaracteresIguales", typeof(bool));
    
            var caseSensitiveParameter = caseSensitive.HasValue ?
                new ObjectParameter("CaseSensitive", caseSensitive) :
                new ObjectParameter("CaseSensitive", typeof(bool));
    
            var caracteresMinimosParameter = caracteresMinimos.HasValue ?
                new ObjectParameter("CaracteresMinimos", caracteresMinimos) :
                new ObjectParameter("CaracteresMinimos", typeof(int));
    
            var cantidadRepeticionesParameter = cantidadRepeticiones.HasValue ?
                new ObjectParameter("CantidadRepeticiones", cantidadRepeticiones) :
                new ObjectParameter("CantidadRepeticiones", typeof(int));
    
            var maxDiasInactividadParameter = maxDiasInactividad.HasValue ?
                new ObjectParameter("MaxDiasInactividad", maxDiasInactividad) :
                new ObjectParameter("MaxDiasInactividad", typeof(int));
    
            var maxDiasCaducidadParameter = maxDiasCaducidad.HasValue ?
                new ObjectParameter("MaxDiasCaducidad", maxDiasCaducidad) :
                new ObjectParameter("MaxDiasCaducidad", typeof(int));
    
            var minutosPermitidosInactividadParameter = minutosPermitidosInactividad.HasValue ?
                new ObjectParameter("MinutosPermitidosInactividad", minutosPermitidosInactividad) :
                new ObjectParameter("MinutosPermitidosInactividad", typeof(int));
    
            var cantIntentosFallidosParameter = cantIntentosFallidos.HasValue ?
                new ObjectParameter("CantIntentosFallidos", cantIntentosFallidos) :
                new ObjectParameter("CantIntentosFallidos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_CONF_PASSWORD_SESION", alfabeticaParameter, numericaParameter, caracteresEspecialesParameter, permiteNrosConsecutivosParameter, permiteLetrasConsecutivasParameter, permiteRepetirPosicionParameter, permiteCaracteresIgualesParameter, caseSensitiveParameter, caracteresMinimosParameter, cantidadRepeticionesParameter, maxDiasInactividadParameter, maxDiasCaducidadParameter, minutosPermitidosInactividadParameter, cantIntentosFallidosParameter);
        }
    
        public virtual int SP_UPDATE_CONF_PASSWORD_TYPE(Nullable<bool> altaAutomatica, Nullable<bool> vincularGrupoWindows, Nullable<bool> solicitarContrasenia, Nullable<bool> soloUsuarioLoggeado, string tipoSeguridad)
        {
            var altaAutomaticaParameter = altaAutomatica.HasValue ?
                new ObjectParameter("AltaAutomatica", altaAutomatica) :
                new ObjectParameter("AltaAutomatica", typeof(bool));
    
            var vincularGrupoWindowsParameter = vincularGrupoWindows.HasValue ?
                new ObjectParameter("VincularGrupoWindows", vincularGrupoWindows) :
                new ObjectParameter("VincularGrupoWindows", typeof(bool));
    
            var solicitarContraseniaParameter = solicitarContrasenia.HasValue ?
                new ObjectParameter("SolicitarContrasenia", solicitarContrasenia) :
                new ObjectParameter("SolicitarContrasenia", typeof(bool));
    
            var soloUsuarioLoggeadoParameter = soloUsuarioLoggeado.HasValue ?
                new ObjectParameter("SoloUsuarioLoggeado", soloUsuarioLoggeado) :
                new ObjectParameter("SoloUsuarioLoggeado", typeof(bool));
    
            var tipoSeguridadParameter = tipoSeguridad != null ?
                new ObjectParameter("TipoSeguridad", tipoSeguridad) :
                new ObjectParameter("TipoSeguridad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_CONF_PASSWORD_TYPE", altaAutomaticaParameter, vincularGrupoWindowsParameter, solicitarContraseniaParameter, soloUsuarioLoggeadoParameter, tipoSeguridadParameter);
        }
    
        public virtual int SP_UPDATE_GRUPOS_WINDOWS(Nullable<int> iD_PERFIL, string gRUPO_WINDOWS, Nullable<bool> sELECTED)
        {
            var iD_PERFILParameter = iD_PERFIL.HasValue ?
                new ObjectParameter("ID_PERFIL", iD_PERFIL) :
                new ObjectParameter("ID_PERFIL", typeof(int));
    
            var gRUPO_WINDOWSParameter = gRUPO_WINDOWS != null ?
                new ObjectParameter("GRUPO_WINDOWS", gRUPO_WINDOWS) :
                new ObjectParameter("GRUPO_WINDOWS", typeof(string));
    
            var sELECTEDParameter = sELECTED.HasValue ?
                new ObjectParameter("SELECTED", sELECTED) :
                new ObjectParameter("SELECTED", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_GRUPOS_WINDOWS", iD_PERFILParameter, gRUPO_WINDOWSParameter, sELECTEDParameter);
        }
    
        public virtual int SP_Update_Perfil(Nullable<int> id, string codigo, string descripcion, Nullable<int> productoId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var productoIdParameter = productoId.HasValue ?
                new ObjectParameter("ProductoId", productoId) :
                new ObjectParameter("ProductoId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Update_Perfil", idParameter, codigoParameter, descripcionParameter, productoIdParameter);
        }
    
        public virtual int SP_Update_Producto(Nullable<int> productoId, string codigo, string descripcion, string base_Path, Nullable<int> tipoPlataformaId, string rama)
        {
            var productoIdParameter = productoId.HasValue ?
                new ObjectParameter("ProductoId", productoId) :
                new ObjectParameter("ProductoId", typeof(int));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var base_PathParameter = base_Path != null ?
                new ObjectParameter("Base_Path", base_Path) :
                new ObjectParameter("Base_Path", typeof(string));
    
            var tipoPlataformaIdParameter = tipoPlataformaId.HasValue ?
                new ObjectParameter("TipoPlataformaId", tipoPlataformaId) :
                new ObjectParameter("TipoPlataformaId", typeof(int));
    
            var ramaParameter = rama != null ?
                new ObjectParameter("Rama", rama) :
                new ObjectParameter("Rama", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Update_Producto", productoIdParameter, codigoParameter, descripcionParameter, base_PathParameter, tipoPlataformaIdParameter, ramaParameter);
        }
    
        public virtual int SP_Update_Tipo_Plataforma(string descripcion, Nullable<int> canLog)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var canLogParameter = canLog.HasValue ?
                new ObjectParameter("CanLog", canLog) :
                new ObjectParameter("CanLog", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Update_Tipo_Plataforma", descripcionParameter, canLogParameter);
        }
    
        public virtual int SP_Update_Usuario(Nullable<int> id, string login, string nombre, string codigo_Persona, string email, Nullable<int> dias_Vigencia_Clave, string login_NT, Nullable<bool> bloqueado, Nullable<bool> bloqueado_Inactividad, string clave, Nullable<bool> cambio_Clave, Nullable<int> cant_Cambios_Clave, Nullable<System.DateTime> ultimo_Cambio_Clave, Nullable<bool> activo, Nullable<int> sectorId, Nullable<int> tipoDocumento, Nullable<int> documento)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigo_PersonaParameter = codigo_Persona != null ?
                new ObjectParameter("Codigo_Persona", codigo_Persona) :
                new ObjectParameter("Codigo_Persona", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var dias_Vigencia_ClaveParameter = dias_Vigencia_Clave.HasValue ?
                new ObjectParameter("Dias_Vigencia_Clave", dias_Vigencia_Clave) :
                new ObjectParameter("Dias_Vigencia_Clave", typeof(int));
    
            var login_NTParameter = login_NT != null ?
                new ObjectParameter("Login_NT", login_NT) :
                new ObjectParameter("Login_NT", typeof(string));
    
            var bloqueadoParameter = bloqueado.HasValue ?
                new ObjectParameter("Bloqueado", bloqueado) :
                new ObjectParameter("Bloqueado", typeof(bool));
    
            var bloqueado_InactividadParameter = bloqueado_Inactividad.HasValue ?
                new ObjectParameter("Bloqueado_Inactividad", bloqueado_Inactividad) :
                new ObjectParameter("Bloqueado_Inactividad", typeof(bool));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            var cambio_ClaveParameter = cambio_Clave.HasValue ?
                new ObjectParameter("Cambio_Clave", cambio_Clave) :
                new ObjectParameter("Cambio_Clave", typeof(bool));
    
            var cant_Cambios_ClaveParameter = cant_Cambios_Clave.HasValue ?
                new ObjectParameter("Cant_Cambios_Clave", cant_Cambios_Clave) :
                new ObjectParameter("Cant_Cambios_Clave", typeof(int));
    
            var ultimo_Cambio_ClaveParameter = ultimo_Cambio_Clave.HasValue ?
                new ObjectParameter("Ultimo_Cambio_Clave", ultimo_Cambio_Clave) :
                new ObjectParameter("Ultimo_Cambio_Clave", typeof(System.DateTime));
    
            var activoParameter = activo.HasValue ?
                new ObjectParameter("Activo", activo) :
                new ObjectParameter("Activo", typeof(bool));
    
            var sectorIdParameter = sectorId.HasValue ?
                new ObjectParameter("SectorId", sectorId) :
                new ObjectParameter("SectorId", typeof(int));
    
            var tipoDocumentoParameter = tipoDocumento.HasValue ?
                new ObjectParameter("TipoDocumento", tipoDocumento) :
                new ObjectParameter("TipoDocumento", typeof(int));
    
            var documentoParameter = documento.HasValue ?
                new ObjectParameter("Documento", documento) :
                new ObjectParameter("Documento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Update_Usuario", idParameter, loginParameter, nombreParameter, codigo_PersonaParameter, emailParameter, dias_Vigencia_ClaveParameter, login_NTParameter, bloqueadoParameter, bloqueado_InactividadParameter, claveParameter, cambio_ClaveParameter, cant_Cambios_ClaveParameter, ultimo_Cambio_ClaveParameter, activoParameter, sectorIdParameter, tipoDocumentoParameter, documentoParameter);
        }
    
        public virtual int SP_Update_Usuario_Primer_Login(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Update_Usuario_Primer_Login", usuarioIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_Usuario_Conectado(string login)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Usuario_Conectado", loginParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> SP_validar_canlog(Nullable<int> usuarioId, Nullable<int> tipoPlataformaId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var tipoPlataformaIdParameter = tipoPlataformaId.HasValue ?
                new ObjectParameter("TipoPlataformaId", tipoPlataformaId) :
                new ObjectParameter("TipoPlataformaId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("SP_validar_canlog", usuarioIdParameter, tipoPlataformaIdParameter);
        }
    
        public virtual ObjectResult<SP_Validate_Password_Attempts_Result> SP_Validate_Password_Attempts(Nullable<int> usuarioId)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Validate_Password_Attempts_Result>("SP_Validate_Password_Attempts", usuarioIdParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> SP_Validate_Password_Repetition(Nullable<int> usuarioId, string clave)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("SP_Validate_Password_Repetition", usuarioIdParameter, claveParameter);
        }
    
        public virtual ObjectResult<SP_Validate_Repeating_Password_Position_Result> SP_Validate_Repeating_Password_Position(Nullable<int> usuarioId, string nuevaClave)
        {
            var usuarioIdParameter = usuarioId.HasValue ?
                new ObjectParameter("UsuarioId", usuarioId) :
                new ObjectParameter("UsuarioId", typeof(int));
    
            var nuevaClaveParameter = nuevaClave != null ?
                new ObjectParameter("NuevaClave", nuevaClave) :
                new ObjectParameter("NuevaClave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Validate_Repeating_Password_Position_Result>("SP_Validate_Repeating_Password_Position", usuarioIdParameter, nuevaClaveParameter);
        }
    
        public virtual ObjectResult<SP_Validate_Usuario_Result> SP_Validate_Usuario(string login, string email, Nullable<int> userId)
        {
            var loginParameter = login != null ?
                new ObjectParameter("Login", login) :
                new ObjectParameter("Login", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Validate_Usuario_Result>("SP_Validate_Usuario", loginParameter, emailParameter, userIdParameter);
        }
    }
}
