//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBaseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONALIDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUNCIONALIDAD()
        {
            this.PERMISO_FUNCIONALIDAD = new HashSet<PERMISO_FUNCIONALIDAD>();
            this.PERMISO_USUARIO = new HashSet<PERMISO_USUARIO>();
        }
    
        public int Id { get; set; }
        public int ProductoId { get; set; }
        public int FeatureId { get; set; }
        public int ProgramaId { get; set; }
        public int FuncionId { get; set; }
    
        public virtual FEATURE FEATURE { get; set; }
        public virtual FUNCION FUNCION { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual PROGRAMA PROGRAMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISO_FUNCIONALIDAD> PERMISO_FUNCIONALIDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISO_USUARIO> PERMISO_USUARIO { get; set; }
    }
}
