//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBaseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_PLATAFORMA
    {
        public int Id { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Terminal { get; set; }
        public string IngresoEgreso { get; set; }
        public Nullable<int> TipoPlataformaId { get; set; }
    
        public virtual TIPO_PLATAFORMA TIPO_PLATAFORMA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
