//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBaseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationLog
    {
        public long Id { get; set; }
        public string Tags { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> ActionTimeStamp { get; set; }
        public string JsonData { get; set; }
        public string ContextSessionId { get; set; }
        public string ContextTransactionId { get; set; }
        public string ContextClientCode { get; set; }
        public string ContextBranchCode { get; set; }
        public string ContextProductCode { get; set; }
        public string ContextFeatureCode { get; set; }
        public string ContextCategoryCode { get; set; }
        public string ContextProgramCode { get; set; }
        public string ContextTerminalId { get; set; }
        public string ContextLogin { get; set; }
    }
}
