//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBaseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFIL_GRUPO_WINDOWS
    {
        public int IdPerfilGrupoWindows { get; set; }
        public int IdPerfil { get; set; }
        public string GrupoWindows { get; set; }
    }
}
