//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBaseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEMA_MIGRATION_LOG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCHEMA_MIGRATION_LOG()
        {
            this.SCHEMA_MIGRATION_GRANTS_LOG = new HashSet<SCHEMA_MIGRATION_GRANTS_LOG>();
        }
    
        public int Id { get; set; }
        public System.DateTime ts { get; set; }
        public System.DateTime deployTimeStamp { get; set; }
        public string scriptName { get; set; }
        public string productName { get; set; }
        public string productVersion { get; set; }
        public string module { get; set; }
        public string tenant { get; set; }
        public string direction { get; set; }
        public bool successDeploy { get; set; }
        public string deployUser { get; set; }
        public string errorMessage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCHEMA_MIGRATION_GRANTS_LOG> SCHEMA_MIGRATION_GRANTS_LOG { get; set; }
    }
}
