//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBaseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEMA_MIGRATION_GRANTS_LOG
    {
        public int Id { get; set; }
        public Nullable<int> IdLogSchemaMigration { get; set; }
        public string @object { get; set; }
        public string login { get; set; }
        public string grantDescription { get; set; }
        public bool successGrant { get; set; }
        public string errorMessage { get; set; }
    
        public virtual SCHEMA_MIGRATION_LOG SCHEMA_MIGRATION_LOG { get; set; }
    }
}
