//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBaseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.CANLOG = new HashSet<CANLOG>();
            this.LOG_PLATAFORMA = new HashSet<LOG_PLATAFORMA>();
            this.MODO_EXCLUSIVO = new HashSet<MODO_EXCLUSIVO>();
            this.PERMISO_USUARIO = new HashSet<PERMISO_USUARIO>();
            this.ULTIMAS_PASSWORD = new HashSet<ULTIMAS_PASSWORD>();
            this.USUARIO_PASSWORD = new HashSet<USUARIO_PASSWORD>();
            this.USUARIO_PERFIL = new HashSet<USUARIO_PERFIL>();
            this.USUARIO_TERMINAL = new HashSet<USUARIO_TERMINAL>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Nombre { get; set; }
        public string Codigo_Persona { get; set; }
        public string Email { get; set; }
        public Nullable<int> Dias_Vigencia_Clave { get; set; }
        public string Login_NT { get; set; }
        public bool Bloqueado { get; set; }
        public bool Bloqueado_Inactividad { get; set; }
        public string Clave { get; set; }
        public Nullable<bool> Cambio_Clave { get; set; }
        public Nullable<int> Cant_Cambios_Clave { get; set; }
        public Nullable<System.DateTime> Ultimo_Cambio_Clave { get; set; }
        public bool Activo { get; set; }
        public Nullable<int> NumeroDocumento { get; set; }
        public Nullable<int> TipoDocumentoId { get; set; }
        public string BloqueadoPor { get; set; }
        public Nullable<System.DateTime> FechaBloqueo { get; set; }
        public string MotivoBloqueo { get; set; }
        public string EliminadoPor { get; set; }
        public Nullable<System.DateTime> FechaEliminado { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<bool> PrimerLogin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CANLOG> CANLOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_PLATAFORMA> LOG_PLATAFORMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MODO_EXCLUSIVO> MODO_EXCLUSIVO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISO_USUARIO> PERMISO_USUARIO { get; set; }
        public virtual SECTOR SECTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ULTIMAS_PASSWORD> ULTIMAS_PASSWORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_PASSWORD> USUARIO_PASSWORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_PERFIL> USUARIO_PERFIL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_TERMINAL> USUARIO_TERMINAL { get; set; }
    }
}
